### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by S0ly** [Ctrlpanel-gg/panel#939] opened 2024-04-03 19:49 UTC
### Feature Description

I would like an option so that the price per hours or month or a product not UP it different of wen its DOWN so it can encourage people to not keep product UP if they have no reason for

### Solution Idea

it would be nice to have an option for the price wen the product is UP and the price wen the product is DOWN

### Additional Info

if its possible of course ;p thanks !

**Comment by sybetjeh** [comment] 2024-04-03 20:01
This has already been suggested many times and is always closed as not planned.

This makes no sense, since Pterodactyl will not give those resources back if a server is offline. It's literally impossible for us to implement, without making obnoxious workarounds that we don't want to.

**Comment by S0ly** [comment] 2024-04-03 20:04
the ram in ptero can be over allocated and the CPU is not assigned so if something is down the CPU core are free for maybe other services

**Comment by sybetjeh** [comment] 2024-04-03 20:05
If you want it, you can do dev4hire and implement it that way. This is unlikely to get implemented in core CPGG.

**Comment by S0ly** [comment] 2024-04-03 20:08
that's sad that many people requested it but its still being refused for no good reason

**Comment by S0ly** [comment] 2024-04-03 20:08
pterodactyl already handle this type of situation so why not cpgg

**Comment by sybetjeh** [comment] 2024-04-03 20:10
I'm not going to recite every reason, you can view the original PR here: https://github.com/Ctrlpanel-gg/panel/issues/757

**Comment by S0ly** [comment] 2024-04-03 20:12
the issue have not really been closed seing the conversation they are just wondering how to implement it

**Comment by sybetjeh** [comment] 2024-04-03 20:15
Sir, it's been open since last year. A miracle will need to happen for core contributors coding it, pushing it to the dev branch, testing it and then merging it to production

**Comment by S0ly** [comment] 2024-04-03 20:16
yep that the magic of open source ;p

**Comment by sybetjeh** [comment] 2024-04-03 20:20
Duplicate of https://github.com/Ctrlpanel-gg/panel/issues/757

**Closed by sybetjeh** 2024-04-03 20:20 UTC
Labels: feature
