### ISSUE TITLE
Option for admins to create servers with custom parameters

### ISSUE THREAD

**Issue by anondev-sudo** [Ctrlpanel-gg/panel#65] opened 2021-06-13 19:38 UTC
There should be admins can create servers for users with custom plan (that they set the specs when creating server on dash)
As some customer asked if he could have mysql database to his server for some credits monthly, but I don't want to create new plan with mysql for just him.

**Comment by S0ly** [comment] 2024-05-18 01:44
seems like a duplicate of #239 so I'm gonna close this one

**Closed by S0ly** 2024-05-18 01:44 UTC
Labels: Feature, Low Priority
