### ISSUE TITLE
[feature] Addons

### ISSUE THREAD

**Issue by expxx** [Ctrlpanel-gg/panel#381] opened 2022-02-02 01:40 UTC
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*
I want to be able to add custom extra items, like 
![image](https://user-images.githubusercontent.com/68918014/152079021-381ce240-14c7-40d0-9e65-74bdb9b6ef2b.png)
something like that, I'd like to be able to add custom packages like `Server Setup`, `DynMAP Setup`, etc
(Write your answer here.)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(Describe your proposed solution here.)
There should be a tab like the packages, and we set a `ONE TIME` credits price, and then if they select it, they get charged for a ONETIME thing, then it shows a screen / sends a email with a custom message or smth. because there isn't a way to claim it without sending proof of purchase to staff
### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by sennecoolgames** [comment] 2023-12-06 10:04
That would be awesome

**Comment by S0ly** [comment] 2024-11-10 02:31
looks like a duplicate of #239

**Closed by S0ly** 2024-11-10 02:31 UTC
Labels: Feature, Low Priority
