### ISSUE TITLE
[Feature] Subscription-Based Payment Option

### ISSUE THREAD

**Issue by Huguitis** [Ctrlpanel-gg/panel#906] opened 2023-08-22 11:52 UTC
### Feature Description

I'd like to put forward a suggestion for a feature that I believe could be beneficial for both users and the development team. Currently, the credit-based payment system for hourly server usage is a great feature, but I'd like to propose the addition of an alternative option.

My idea is to allow users to opt out of using credits and, instead, use direct money subscriptions. This would mean that users could set up a subscription for their servers, where they would be automatically charged on a recurring basis until they decide to cancel.

I believe this feature could simplify financial management for users and make the payment process more convenient. Additionally, it could be an opportunity for the development team to offer different payment options, which could be mutually beneficial.

Of course, I understand that this could be a significant change to the current structure, but I believe it could enhance the overall user experience. I'm excited to hear your thoughts on this idea and whether it's possible to consider its implementation in future updates.

### Solution Idea

**Proposed Implementation:**

Incorporating the subscription-based payment option into CtrlPanrl entails the integration of a new billing method alongside the existing credit-based system. Users will have the flexibility to opt for the current credit-based system or transition to the novel subscription-based model.

1. **Subscription Setup:**
   - Users should have the ability to select a subscription plan tailored to their server requirements. Subscription plans can be structured with different tiers, offering distinct server resources and features at varying price points.
   - Users will be able to choose their preferred billing cycle for the subscription (e.g., monthly, quarterly, annually).

2. **Payment Integration:**
   - Users should securely input their payment information using the available integration options, such as Mollie, Stripe, or PayPal.
   - Payment information must be securely stored, adhering to industry-standard security protocols.

3. **Automatic Billing:**
   - Following subscription, the system should automatically initiate charges using the integrated payment method, in accordance with the chosen billing cycle.
   - Users should receive timely notifications regarding upcoming charges and have the ability to review their billing history.

4. **Cancellation and Management:**
   - Users should have the convenience of canceling their subscription at any time. Upon cancellation, the server's resources should be adjusted accordingly.

**Reasons for Implementation:**

1. **User Convenience:**
   - Subscription-based payments offer users ease of use, removing the need for manual credit top-ups or renewal actions. This simplifies the payment process.

2. **Predictable Billing:**
   - Subscriptions provide users with consistent billing cycles, facilitating better financial planning.

3. **Simplified Financial Management:**
   - Users can rest assured that their servers will continue to operate as long as the subscription is active, eliminating the need for continuous credit level monitoring.

4. **Diversified Revenue Streams:**
   - Incorporating subscription options opens up new revenue avenues. Users favoring subscriptions may opt for higher-tier plans, potentially increasing revenue potential.

5. **Competitive Edge:**
   - Offering both credit-based and subscription-based models enhances CtrlPanel's competitive stance, catering to a wider array of user preferences.

6. **Flexible Integration:**
   - The development team can explore partnerships with payment processors like Mollie, Stripe, or PayPal, offering users multiple payment methods while generating revenue through transaction fees.

**Comment by GeckoBoy84** [comment] 2023-08-22 13:11
CtrlPanel is a credit based billing platform. That is its purpose, to use credits not money for each

**Comment by GeckoBoy84** [comment] 2023-08-22 13:12
CtrlPanel is a credit based billing panel. That is its purpose, not for servers to be individually billed with real money. It’s highly unlikely this would be changed in the public panel.

**Comment by nuallan89** [comment] 2023-09-07 18:34
Would an auto top up function work when credit is too low? Something that the client would be able to activate or deactivate at wish?

**Comment by S0ly** [comment] 2024-05-18 01:50
so this is a duplicate of #138 but its very detailed and a pretty cool idea I will mention in in 138 to keep an eye on it

**Closed by S0ly** 2024-05-18 01:50 UTC
Labels: Feature
