### ISSUE TITLE
[Bug]: Incorrect display of the product on the user's viewing page / v0.10

### ISSUE THREAD

**Issue by MrWeez** [Ctrlpanel-gg/panel#935] opened 2024-03-03 20:44 UTC
### What is your request about?

The server product name is displayed incorrectly on the /admin/users/<user_id> page. The error is like in this [issue](https://github.com/Ctrlpanel-gg/panel/issues/756), but in a different place.

### Branch

development

### Additional Info

![image](https://github.com/Ctrlpanel-gg/panel/assets/64205495/5c76bb01-7fe2-4dea-a9f2-3de094d8017e)

**Comment by S0ly** [comment] 2024-05-17 13:20
im confused where do you see it display incorrectly ?

**Comment by MrWeez** [comment] 2024-05-17 13:22
> im confused where do you see it display incorrectly ? because the name is here maybe because it says product and not description ?

It displays the description of the product, not its name. This problem was elsewhere, I attached a link in the message above.

**Comment by S0ly** [comment] 2024-05-17 13:24
yes but the name is not already here ? 
![image](https://github.com/Ctrlpanel-gg/panel/assets/86328249/515dff1c-04a1-4981-8d65-b5dd6ae5f969)

**Comment by MrWeez** [comment] 2024-05-17 13:25
> yes but the name is not already here ? ![image](https://private-user-images.githubusercontent.com/86328249/331609326-515dff1c-04a1-4981-8d65-b5dd6ae5f969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTI2MjYsIm5iZiI6MTcxNTk1MjMyNiwicGF0aCI6Ii84NjMyODI0OS8zMzE2MDkzMjYtNTE1ZGZmMWMtMDRhMS00OTgxLThkNjUtYjVkZDZhZTVmOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkY2NjMGQ3Yzg0Zjk5ZDlhY2Q3MWI1NTVmYWE3N2M0NjBmMWQ4YzE0NzAwZWE4MGRmZDlmMTJiY2IyOTU4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-B3bK4lgSSz6lh2gJL3mjx6HYHPNyl9_eWeHLhOWYyk)

This is the name of the server, not its product

**Comment by S0ly** [comment] 2024-05-17 13:26
ho okay I'm still confused xD I will add it to the panel fix branch

**Comment by kenshin133** [comment] 2024-05-18 00:16
To show this more clearly, 
Here is the product :

![image](https://github.com/Ctrlpanel-gg/panel/assets/29851415/3740175b-9efa-435e-809b-478a6ccc0fed)
and here is under my user (this is in main branch.. but the issue is not new) 

![image](https://github.com/Ctrlpanel-gg/panel/assets/29851415/33b34d51-d015-4142-a22b-885205b54e12)

**Comment by S0ly** [comment] 2024-05-18 00:18
hooo okay

**Comment by kenshin133** [comment] 2024-05-22 00:55
Checked into this a bit, in admin/users/show.blade.php which seems to be the right location for this, the datatables are calling the right thing: 
                {
                    data: 'resources',
                    name: 'product.name'
                },
                
                In database product.name is correct. Will check into this a bit more.

**Comment by kenshin133** [comment] 2024-05-22 01:12
I figured out the fix, but dont know why it works so someone else needs to follow up on this one. 

The change is line 186 of app/Http/Controllers/Admin/ServerController.php

Changed from "return $server->product->description;"

to "return $server->product->name;"

**Comment by S0ly** [comment] 2024-05-22 07:23
If you get the description instread lf the name your fix make sense

**Comment by kenshin133** [comment] 2024-05-22 13:37
The fix makes sense and that's how I found it, but I'm not 100% sure this value isn't used elsewhere. 

So I've posted in hopes someone else quickly gives it a pass or fail when they get around to it. its a pretty minor issue. (and possibly up to preference)

**Comment by kenshin133** [comment] 2024-05-22 14:42
#957 would fix this

**Comment by MrWeez** [comment] 2024-05-22 14:45
@S0ly can you link the issue to the PR? Thx.

**Comment by S0ly** [comment] 2024-05-22 15:03
@MrWeez yes thanks, ask @1day2die for permission so you can do it 😅

**Closed** 2024-05-22 20:49 UTC
Labels: Bug / Fix, Medium Priority
